node {

    def imageTag = "peterngtr/rest-demo:${env.BUILD_NUMBER}"
    def dockerHome = tool 'myDocker'

    stage("Initializing") {
        cleanWs();
        checkout scm;
        sh 'git reset --hard'
        env.PATH = "${dockerHome}/bin:${env.PATH}"
    }

    stage("Building Images") {
        sh "docker build -t ${imageTag} -f docker/Dockerfile ."
    }

    stage("Running Tests") {
        try {
            sh "npm i"
            sh "npx codeceptjs run --steps"
            sh "npx allure generate output -o report"
        }
        finally {
            sh "ls report"
            // allure includeProperties: false, jdk: '', results: [[path: 'allure-results']]
        }
    }


}
