name: Use Central Publish Workflow

on:
  push:
    branches:
      - master
      - main

jobs:
  call-publish:
    uses: kobenguyent/actionsmith/.github/workflows/publish-npm.yml@main
    secrets:
      npm_token: ${{ secrets.npm_token }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
