name: API Tests - Allure Reports

on:
  push:
    branches-ignore:
      - '!master' # ignore gh-pages

env:
  NODE_VERSION: 22
  CI_BUILD_NUMBER: ${{ github.run_number }}

permissions:
  contents: write
  pages: write
  id-token: write
  actions: read

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  lint-check:
    uses: kobenguyent/actionsmith/.github/workflows/lint-check.yml@main

  acceptance-tests:
    needs: [lint-check]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          npm i
          npx playwright install

      - name: Run tests and generate Allure report
        run: |
          npm run test
          npm run allure-reports-generate
          #execute this command for local to access allure reports
          #npm run allure-reports-patch
        env:
          MAILINATOR_TOKEN: ${{ secrets.MAILINATOR_TOKEN }}
          MAILINATOR_DOMAIN: ${{ secrets.MAILINATOR_DOMAIN }}
          REQRES_TOKEN: ${{ secrets.REQRES_TOKEN }}
  generate-and-deploy-allure-report:
    needs: [acceptance-tests]

    uses: kobenguyent/actionsmith/.github/workflows/deploy-allure-gh-pages.yml@main
    with:
      allure_results: output
      allure_history: allure-history/allure-history
      publish_dir: allure-history/allure-history