name: Acceptance Tests

on:
  push:
    branches-ignore:
      - '!master' # ignore gh-pages

env:
  NODE_VERSION: 22
  CI_BUILD_NUMBER: ${{ github.run_number }}

permissions:
  contents: write
  pages: write
  id-token: write
  actions: read

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm run lint

  acceptance-tests:
    needs: [lint-check]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          npm i
          npx playwright install

      - name: Run tests and generate Allure report
        run: |
          npm run test
          npm run allure-reports-generate
          npm run allure-reports-patch
        env:
          MAILINATOR_TOKEN: ${{ secrets.MAILINATOR_TOKEN }}
          MAILINATOR_DOMAIN: ${{ secrets.MAILINATOR_DOMAIN }}

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: output/allure/
          allure_history: output/allure/history
          keep_reports: 5

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output/allure
        env:
          PUBLISH_BRANCH: gh-pages
